var paths = {
    "@hpcc-js/api": "https://cdn.jsdelivr.net/npm/@hpcc-js/api@2.8.46/dist/index.min",
    "@hpcc-js/chart": "https://cdn.jsdelivr.net/npm/@hpcc-js/chart@2.61.0/dist/index.min",
    "@hpcc-js/codemirror": "https://cdn.jsdelivr.net/npm/@hpcc-js/codemirror@2.43.0/dist/index.min",
    "@hpcc-js/common": "https://cdn.jsdelivr.net/npm/@hpcc-js/common@2.51.0/dist/index.min",
    "@hpcc-js/comms": "https://cdn.jsdelivr.net/npm/@hpcc-js/comms@2.48.0/dist/index.min",
    "@hpcc-js/composite": "https://cdn.jsdelivr.net/npm/@hpcc-js/composite@2.5.69/dist/index.min",
    "@hpcc-js/dgrid": "https://cdn.jsdelivr.net/npm/@hpcc-js/dgrid@2.12.0/dist/index.min",
    "@hpcc-js/form": "https://cdn.jsdelivr.net/npm/@hpcc-js/form@2.8.55/dist/index.min",
    "@hpcc-js/graph": "https://cdn.jsdelivr.net/npm/@hpcc-js/graph@2.61.0/dist/index.min",
    "@hpcc-js/html": "https://cdn.jsdelivr.net/npm/@hpcc-js/html@2.26.0/dist/index.min",
    "@hpcc-js/layout": "https://cdn.jsdelivr.net/npm/@hpcc-js/layout@2.29.0/dist/index.min",
    "@hpcc-js/map": "https://cdn.jsdelivr.net/npm/@hpcc-js/map@2.54.0/dist/index.min",
    "@hpcc-js/observable-md": "https://cdn.jsdelivr.net/npm/@hpcc-js/observable-md@2.35.0/dist/index.min",
    "@hpcc-js/other": "https://cdn.jsdelivr.net/npm/@hpcc-js/other@2.13.62/dist/index.min",
    "@hpcc-js/phosphor": "https://cdn.jsdelivr.net/npm/@hpcc-js/phosphor@2.14.42/dist/index.min",
    "@hpcc-js/react": "https://cdn.jsdelivr.net/npm/@hpcc-js/react@2.34.0/dist/index.min",
    "@hpcc-js/timeline": "https://cdn.jsdelivr.net/npm/@hpcc-js/timeline@2.32.0/dist/index.min",
    "@hpcc-js/tree": "https://cdn.jsdelivr.net/npm/@hpcc-js/tree@2.24.0/dist/index.min",
    "@hpcc-js/util": "https://cdn.jsdelivr.net/npm/@hpcc-js/util@2.32.0/dist/index.min",
    "d3-dsv": "https://cdn.jsdelivr.net/npm/d3-dsv@1.2.0/dist/d3-dsv.min",
    "d3-fetch": "https://cdn.jsdelivr.net/npm/d3-fetch@1.2.0/dist/d3-fetch.min",
    "tslib": "https://cdn.jsdelivr.net/npm/tslib@2.3.0/tslib"
};

var debugPaths = {
    "@hpcc-js/api": "../../hpcc-js/packages/api/dist/index",
    "@hpcc-js/chart": "../../hpcc-js/packages/chart/dist/index",
    "@hpcc-js/codemirror": "../../hpcc-js/packages/codemirror/dist/index",
    "@hpcc-js/common": "../../hpcc-js/packages/common/dist/index",
    "@hpcc-js/comms": "../../hpcc-js/packages/comms/dist/index",
    "@hpcc-js/composite": "../../hpcc-js/packages/composite/dist/index",
    "@hpcc-js/dgrid": "../../hpcc-js/packages/dgrid/dist/index",
    "@hpcc-js/form": "../../hpcc-js/packages/form/dist/index",
    "@hpcc-js/graph": "../../hpcc-js/packages/graph/dist/index",
    "@hpcc-js/html": "../../hpcc-js/packages/html/dist/index",
    "@hpcc-js/layout": "../../hpcc-js/packages/layout/dist/index",
    "@hpcc-js/map": "../../hpcc-js/packages/map/dist/index",
    "@hpcc-js/observable-md": "../../hpcc-js/packages/observable-md/dist/index",
    "@hpcc-js/other": "../../hpcc-js/packages/other/dist/index",
    "@hpcc-js/phosphor": "../../hpcc-js/packages/phosphor/dist/index",
    "@hpcc-js/react": "../../hpcc-js/packages/react/dist/index",
    "@hpcc-js/timeline": "../../hpcc-js/packages/timeline/dist/index",
    "@hpcc-js/tree": "../../hpcc-js/packages/tree/dist/index",
    "@hpcc-js/util": "../../hpcc-js/packages/util/dist/index",
    "d3-dsv": "../node_modules/d3-dsv/dist/d3-dsv.min",
    "d3-fetch": "../node_modules/d3-fetch/dist/d3-fetch.min",
    "tslib": "../node_modules/tslib/tslib"
};
